imputnet/cobalt

src/modules/services/_config.json

When sharing from TikTok via the app, some URLs show up as:
https://www.tiktok.com/t/:ID/?k=1, similar to vm.tiktok.com/:ID urls, cobalt doesn't recognize the first style of links.
This should fix that, I think.
Edit: I've tested this with multiple videos, it works.

Support for tiktok's /t/ URLs.

---

src/cobalt.js

#98 
- Add `cors()` middleware to `/api/:type` route allowing CORS requests.
- Remove other instances of middleware.

change: enable CORSon `/api/:type`

---

src/modules/setup.js

- When running the setup script, allow the user to enable CORS for their instance. It is disabled by default.

feat(setup): add cors option to setup script

---

src/cobalt.js

This PR moves the conditions that determine whether or not Cobalt should start hosting the API or the web client into external constants to improve code quality.

Extract startup conditions to consts

---

src/modules/stream/types.js

prevents reverse proxies (namely nginx) from assuming the server died because of an empty response
specifically, this handles the situation where an exception / error occurs before any headers are set

always send something on stream failure

---

.github/workflows/docker.yml

should hopefully make it easier for people to just run cobalt with one composefile and nothing else

Create Docker image build GitHub action

---

src/modules/processing/matchActionDecider.js
src/modules/processing/servicesConfig.json

cobalt currently serves a m3u file for soundcloud downloads with `audioQuality` set to best which is obviously not intended
this fixes it kthx

fix soundcloud downloads when requested format is `best`

---

package.json
src/modules/stream/types.js

- try to close as many things as possible when shutting down
- remove redundant (e.g. `exit` on process when listening for `close`) and straight up useless (`disconnect`) event listeners
- send SIGKILL to ffmpeg process after timeout in case the ffmpeg process decides to hang when SIGTERM'd
- cleanup

improve stream shutdown handling

---

src/front/robots.txt

currently the robots.txt file is useless because it's interpreted as one path "/icons/ /fonts/ *.js *.css"
(an example path that would be accepted (and therefore disallowed on scrapers) by this regex would be `https://cobalt.tools/icons/ /fonts/ bla.js .css`, which is obviously nonsense & useless)

fix robots.txt

---

README.md
src/modules/processing/services/twitch.js

Would be good for twitch clips to use their titles, so this should work fine.
I could also do tiktok but I might have to remove hashtags for that.

feat: add filename attributes to twitch clips

---

src/front/cobalt.js

prevents shortcuts from getting triggered by accident when manually typing out url

front: ignore shift+key combinations if url bar is focused

---

src/front/cobalt.css

For some reason, chromium-based browsers show blurry contents inside `#popup-content` divs with a double valued border-radius. It doesn't happen on Firefox.
<details>
<summary>Screenshots</summary>
> (before, in prod)
---
> (after, with fix)
---
> (firefox is fine)
</details>
Safari still renders blurry text, though this border-radius PR does not fix it.
The `translate` of the `transform` property from the `.center` class is the culprit, as you can see in the two screenshots below. This might need more time to fix, that's why I didn't look into it yet. This little PR will already fix this issue for most users though.
<details>
<summary>Screenshots</summary>
---
</details>

cobalt.css: fix blurry text on modal contents

---

src/modules/processing/matchActionDecider.js

gif download with audio muted should not produce an mp4

matchActionDecider: reprioritize gif action above audio settings

---

package.json
src/core/api.js
src/modules/sub/utils.js

allows for more versatile configurations that do not necessarily have to use cloudflare
works with:
+ accessing port 9000 directly -> req.ip is actual ip, xff is ignored
+ no cloudflare, reverse proxy (caddy: default config, nginx: needs `add_header`)
+ cloudflare (nginx: default config*, caddy: needs `trusted_proxies`)
\* if the server is incorrectly setup and accessible not just via cloudflare but directly (no ip allowlist and/or no origin certificate), user can set the xff header to whatever they want (but the current version of cobalt also has this issue lol)
(note: by "default config" i mean the bare minimum to proxy cobalt through that particular webserver)
also ratelimits IPv6 addresses by prefix instead of individual addresses
i set it at /56, which should not be too strict (yet …

api: proper rate limiting (including limiting ipv6 by prefix)

---

src/modules/processing/services/youtube.js

fixes https://discord.com/channels/1049706293700591677/1049740124231061555/1163870548854579322:
> It appears that some YouTube videos (like this one https://youtube.com/watch?v=uuAgccyZVJ8) are handled a bit weirdly by the quality settings, in particular this one cannot be downloaded in 144p or 240p and if these are provided as parameters to the API it downloads at the default 720p instead. Downloading at 360p works normally however. This only appears to affect some videos (such as some others uploaded on this channel) and most videos are downloaded as expected at 144 or 240p

youtube: unify quality matching, slight cleanup

---

docs/run-an-instance.md

Noticed this was missing when I was updating my environment variables.

docs/api: add missing 'API_URL' to web

---

src/modules/stream/manage.js

- no longer throws an incorrect type of error
- checks whether cache exists before attempting to decrypt it

stream/manage: fix and clean up verifyStream function

---

docs/examples/docker-compose.example.yml

To prevent other people like me: https://github.com/wukko/cobalt/issues/435 from running into this if they rush into  deploying the compose file. 
> imo a COOKIE_PATH example should also be included in the compose file if a volume suggestion for it is offered, or alternatively, in the app try to read COOKIE_PATH and if it doesn't exist read /cookies.json. I didn't read the table at the bottom under the docker compose section and I actually found this out from cloning the source code and searching for cookie lol

docs/example/docker: Add COOKIE_PATH example to compose

---

src/modules/stream/manage.js

fix(internal-streams): fallback `API_PORT` env variable to default

---

docs/examples/cookies.example.json
src/modules/processing/services/instagram.js

for total of SEVEN methods of getting post info
i cannot bear this anymore

instagram: add fetching using bearer token & prevent repetitive oembed pulling 

---

README.md
src/modules/processing/services/pinterest.js
src/modules/processing/servicesConfig.json
src/test/tests.json

Pretty simple pull request, implemented support for pictures and gifs for Pinterest as suggested in #439. 
Not sure how necessary pictures are, but gifs will be very useful as user needs to register or open devtools to download them :3
There is no support for "slides", if they still exist, which I'm not sure since I haven't used Pinterest for a long time, or they just don't show up for unauthorized users. (I tried to find them, and failed :D).

pinterest: implement image and gifs support

---

src/modules/processing/match.js
src/modules/processing/matchActionDecider.js
src/modules/processing/services/tiktok.js
src/modules/stream/shared.js

fixes #497
test instance available at [web.eepy.today](https://web.eepy.today)

tiktok: use webapp-based downloading method

---

src/modules/processing/services/youtube.js

cobalt api has been getting blocked for (up to) several seconds during startup, and also crashing when unable to connect to youtube (e.g. when it's blocked); this should fix both those things
closes #521

youtube: don't block api startup waiting for innertube to activate

---

src/modules/pageRender/page.js

This adds the "data-form-type" attribute "other" which stops Dashlane from auto filling. 
https://dashlane.github.io/SAWF/#data-form-type-attribute-other-value

web: stop password managers from autofilling data into url area

---

src/core/api.js
src/modules/sub/randomize-ciphers.js

this makes cobalt less prone to TLS client fingerprinting, as it avoids having the default node.js TLS fingerprint that is shared by all node.js applications.
also seemingly fixes #573

api: randomize cipherlist for making requests to services

---

src/util/tests.json

This fixes 2 of the Twitter links. 
* `TwitterSpaces` account is now `XSpaces`, was failing the test before. Renaming fixes it.
* The `Twitter` account is private, so the mixed media test was failing. This replaces it with a random tweet I found that has a photo, video, and gif.

tests: fix broken twitter links

---

README.md
src/modules/processing/match.js
src/modules/processing/matchActionDecider.js
src/modules/processing/services/facebook.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js
src/modules/processing/url.js
src/util/tests.json

feat: add facebook support

---

docs/run-an-instance.md
src/core/api.js
src/modules/config.js

added support for `API_EXTERNAL_PROXY` env variable that sets up a global undici dispatcher
definitely not the best way to do this (i really dislike relying on globals), but did it like this anyway because:
- there isn't a single common wrapper over `fetch()` where i could provide a `dispatcher`
- passing it manually everywhere is very tedious and error-prone (especially considering there aren't any types)
- since api is supposed to run in a separate isolated process it probably won't affect what it isn't supposed to
one thing i worry about is the youtube handler which mentions reading `dispatcher` from `streamInfo`, but i couldn't find a place where it is being passed there 🧐

feat: support external proxies

---

web/i18n/en/settings.json
web/src/routes/about/privacy/+page.svelte

- Tweak spelling for various tenses of `tunnel`
- When used in the networking sense, it is much more common to use the American version which uses one L.

Spellcheck: Tweak spelling for various tenses of `tunnel`

---

web/src/components/misc/Toggle.svelte
web/src/routes/+layout.svelte

- Use `var(--green)` as active background color
- There is currently a good amount of difficulty in determining which toggles are enabled and disabled, especially for the visually impaired. I propose we use an active color with more contrast to the inactive color.

web/layout: increase toggle contrast in dark mode

---

api/src/util/setup.js

api/setup: use pnpm instead of npm

---

Dockerfile
api/package.json
api/src/cobalt.js
api/src/config.js
api/src/core/api.js
api/src/misc/cluster.js
api/src/misc/crypto.js
api/src/processing/cookie/cookie.js
api/src/processing/cookie/manager.js
api/src/processing/services/bluesky.js
api/src/processing/services/instagram.js
api/src/processing/services/snapchat.js
api/src/processing/services/tiktok.js
api/src/processing/services/twitter.js
api/src/security/api-keys.js
api/src/security/secrets.js
api/src/store/base-store.js
api/src/store/memory-store.js
api/src/store/redis-ratelimit.js
api/src/store/redis-store.js
api/src/store/store.js
api/src/stream/manage.js
api/src/util/test-ci.js
docs/run-an-instance.md
pnpm-lock.yaml

- adds support for storing cache data in redis, configurable with `API_REDIS_URL` env (`redis://localhost:6379`)
- adds ability to spawn multiple cross-communicating cobalt processes using `node:cluster`, configured with `API_INSTANCE_COUNT` env
- requires `API_REDIS_URL` to be configured
- ratelimit and stream cache exclusively stored in redis
- istream cache stored locally on each instance, istreams are bound to specific instance that is serving the stream
- main instance fetches cookies/api keys, distributes them amongst newly spawned processes
- works on linux, node >= 23.1.0

multi-process concurrent cobalt instances

---

docs/run-an-instance.md

Noticed this was missing, so here it is.

docs/run-an-instance: add missing `DISABLED_SERVICES`

---

api/src/processing/create-filename.js
api/src/processing/match-action.js
api/src/processing/match.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/vk.js
api/src/stream/shared.js
api/src/util/tests/vk.json
web/i18n/en/error.json

api/vk: use proper api, add support for more links & access keys, refactor

---

api/src/processing/match-action.js

api/match-action: pass audio bitrate when creating tiktok stream

---

api/src/misc/utils.js
api/src/processing/match-action.js
api/src/processing/match.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/xiaohongshu.js
api/src/processing/url.js
api/src/util/tests/bsky.json
api/src/util/tests/pinterest.json
api/src/util/tests/xiaohongshu.json
docs/api.md
web/i18n/en/settings.json
web/src/routes/settings/video/+page.svelte

api: add support for xiaohongshu (rednote)

---

api/src/core/api.js
api/src/misc/utils.js
api/src/processing/match-action.js
api/src/processing/services/youtube.js
api/src/stream/internal.js
api/src/stream/manage.js
api/src/stream/stream.js

sometimes, the url that we are downloading from stops working.
a transplant takes note of this, and attempts to re-request the url in hopes of it working again

api: itunnel transplants

---

api/src/processing/url.js

This is in response to #799.
It's not really a bug, but the original code intended the ID for Loom videos to be at most 32 characters. For example, `https://www.loom.com/share/4a2a8baf124c4390954dcbb46a58cfd7`.
However, apparently Loom has a longer URL variant that has the title encoded as well such as `https://www.loom.com/share/Unlocking-Incredible-Organizational-Velocity-with-Async-Video-4a2a8baf124c4390954dcbb46a58cfd7`.
However, I did notice that in this longer variant URL form, the URL actually contains the ID right at the end of the path. For example in `https://www.loom.com/share/Unlocking-Incredible-Organizational-Velocity-with-Async-Video-4a2a8baf124c4390954dcbb46a58cfd7`, the ID of the video is `4a2a8baf124c4390954dcbb46a58cfd7`.
So, what I did is pretty much utilize the …

api/url: extract loom video id from longer links

---

api/package.json
api/src/config.js
api/src/processing/services/youtube.js
pnpm-lock.yaml

this PR also changes the default client to IOS, so CUSTOM_INNERTUBE_CLIENT is no longer needed to get youtube functionality to work
closes #1173

api: update youtube.js, switch between ios & web_embedded clients depending on request

---

api/src/processing/service-config.js
api/src/processing/services/tiktok.js

links copied from tiktok lite use a different structure.
```bash
curl https://vm.tiktok.com/ZSrRvKqDW/
<a href="https://t.tiktok.com/i18n/share/video/7455415590421859617/?...">Moved Permanently</a>.
```
* [`api/src/processing/service-config.js`](diffhunk://#diff-e46dbb2452195cabae3b56ac712455a8c21a68c6e4f44f8c099490922eeb69a3R139-R145): added a new pattern "i18n/share/video/:postId/" 
* [`api/src/processing/service-config.js`](diffhunk://#diff-e46dbb2452195cabae3b56ac712455a8c21a68c6e4f44f8c099490922eeb69a3R139-R145): included "t" as an additional subdomain for tiktok

api/service-config: add tiktok lite url pattern

---

api/src/processing/service-patterns.js

closes #1229 
ids in new share links are longer than 12 characters, i assume that they'll keep growing, so why not bump the limit to 24 chars :3

api/service-patterns: increase xiaohongshu shareId max length

---

web/src/app.css
web/src/components/buttons/Switcher.svelte
web/src/components/changelog/ChangelogEntry.svelte
web/src/components/dialog/PickerDialog.svelte
web/src/components/dialog/PickerItem.svelte
web/src/components/dialog/SavingDialog.svelte
web/src/components/dialog/SmallDialog.svelte
web/src/components/donate/DonateBanner.svelte
web/src/components/donate/DonateCardContainer.svelte
web/src/components/donate/DonateOptionsCard.svelte
web/src/components/donate/DonateShareCard.svelte
web/src/components/misc/FileReceiver.svelte
web/src/components/misc/Placeholder.svelte
web/src/components/queue/ProcessingStatus.svelte
web/src/components/save/Omnibox.svelte
web/src/components/save/SupportedServices.svelte
web/src/components/save/buttons/DownloadButton.svelte
web/src/components/settings/SettingsInput.svelte
web/src/components/subnav/PageNav.svelte
web/src/routes/+page.svelte
web/src/routes/remux/+page.svelte
web/src/routes/updates/+page.svelte

- uses outline instead of box-shadow to not conflict with existing box-shadow on many elements
- shows the focus ring only on clickable elements (button & a)
- removes data-focus-ring-hidden & all other related workarounds
- fixes the focus ring of the processing status button and file receiver

web: proper focus ring

---

api/src/processing/match-action.js
api/src/processing/service-config.js
api/src/stream/ffmpeg.js
api/src/stream/proxy.js
api/src/stream/stream.js
api/src/stream/types.js

- split types.js into ffmpeg.js and proxy.js
- created render() which handles ffmpeg & piping stuff
- merged remux() and merge() into one function
- simplified and cleaned up arguments
- removed headers since they're handled by internal streams now
- removed outdated arguments

api/stream: refactor and simplify ffmpeg-related code

---

api/src/misc/utils.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/xiaohongshu.js
api/src/processing/url.js
api/src/util/tests/xiaohongshu.json

when you share a video (or anything else), you now get a new type of link, example: http://xhslink.com/m/2wAnaTkLRc1
new links don't support the HEAD method (you get a 404 response), so i had to use GET. the content length is ~420 bytes so it shouldn't be that bad.
also, all of the links in tests expired so i replaced them
this is my first contribution to cobalt in some time and i hope i did everything right, if not please tell me :3
<sup>(i downloaded their app on my phone just for this)</sup>

api: support new xiaohongshu links, add fallbacks to getRedirectingURL

---

api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/bilibili.js
api/src/processing/url.js
api/src/util/tests/bilibili.json

different videos share the same id, kind of weird
closes #1170
closes #1261

api/bilibili: add support for video parts/episodes
