imputnet/cobalt

src/modules/pageRender/page.js

Noticed that the clipboard button uses an incorrect aria-label, changed it to the same value as the button text

Adjusted the paste from clipboard aria-label to be correct

---

src/modules/processing/match.js
src/modules/processing/matchActionDecider.js
src/modules/processing/services/pinterest.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js
src/modules/sub/utils.js
src/test/tests.json

Allows to download from pinterest videos and stories.
Test links:
- https://www.pinterest.ca/pin/70437485604616/ (regular)
- https://www.pinterest.ca/pin/gadget-cool-products-amazon-product-technology-kitchen-gadgets--1084663891475263837/ (story)

feat: add pinterest support

---

src/modules/processing/services/instagram.js

no more parsing html with ~~regex~~ `.split()` sorry

fix instagram downloads

---

src/modules/processing/servicesPatternTesters.js

username can actually be up to 25 characters long, song url can actually be up to 255 characters long

fix soundcloud pattern test

---

src/modules/processing/match.js
src/modules/processing/matchActionDecider.js
src/modules/processing/services/streamable.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js
src/test/tests.json

Working:
- Video downloads
- Audio only downloads
- Respects quality picker (streamable only hosts 720p and 360p though)
Not working:
- Muted audio downloads (video plays for first few seconds then

feat: streamable.com support

---

package.json
src/modules/stream/stream.js
src/modules/stream/types.js

might as well since it already comes with youtubei.js

replace got with undici

---

src/modules/processing/matchActionDecider.js

sets a fixed order of how the appropriate `action` is chosen

use else-if instead of if for evaluating action

---

src/modules/processing/cookie/cookie.js
src/modules/processing/cookie/manager.js
src/modules/processing/services/instagram.js

instagram hotfix

---

src/cobalt.js

mostly relevant because frontend does not need an innertube session

import particular mode module only if needed

---

package.json
src/modules/stream/types.js

revert "improve stream shutdown handling" pr as everything broke in prod

---

src/modules/processing/services/reddit.js

reddit: fix expiry check

---

src/modules/api.js
src/modules/processing/match.js
src/modules/processing/services/reddit.js
src/modules/processing/servicesPatternTesters.js
src/modules/sub/utils.js

this currently affects only reddit, but it should get fixed at the core of the problem instead of hacking around it somewhere else in the code
the main problem is that `url-pattern` doesn't like urls containing utf-8 characters (understandably)

fix handling of URLs containing utf-8 characters

---

src/modules/processing/servicesConfig.json

https://old.reddit.com/r/interestingasfuck/comments/1974t3b/how_flies_actually_eat_your_food/?ref=share&ref_source=link
https://de.reddit.com/r/de/comments/126j28m/so_viele_tiere_werden_in_deutschland_gerade/
etc, for a bunch of countries

servicesConfig: enable wildcard subdomains for reddit

---

src/test/tests.json

test: add twitter mediaviewer link 

---

src/modules/processing/match.js
src/modules/processing/services/bilibili.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js
src/modules/processing/url.js
src/modules/stream/types.js
src/test/tests.json

resolves #302
resolves #319
resolves #320

bilibili: fix downloads, add b23.tv and bilibili.tv support

---

src/modules/processing/matchActionDecider.js
src/modules/processing/services/tumblr.js
src/test/tests.json

tumblr: use mobile api & fix audio support

---

.github/workflows/docker.yml

so that github stops complaining about node 16

build: bump action versions

---

src/modules/processing/services/tiktok.js

fixes #390 
TikTok пофиксил возможность получать информацию о видео через `/aweme/v1/feed` на `api2.musical.ly`, `api.tiktokv.com` и некоторых других, но сделал это не везде: на некоторых инстансах это по прежнему работает.
этот PR меняет инстанс на `api22-normal-c-useast2a.tiktokv.com`, где видео по прежнему получить возможно. 
конечно неизвестно, сколько этот фикс проживёт но хоть что-то ¯\_(ツ)_/¯

tiktok: change api host

---

docs/run-an-instance.md
package.json
src/front/cobalt.css
src/localization/languages/en.json
src/modules/processing/match.js
src/modules/processing/services/tiktok.js

closes #396 and #294
remake of #401

fix tiktok downloads

---

src/modules/processing/services/instagram.js
src/modules/processing/services/soundcloud.js

instagram: update api endpoint method, add dtsg token parsing & caching

---

src/modules/processing/servicesConfig.json

servicesConfig: add support for /channels/uploader/id vimeo links

---

src/modules/processing/services/instagram.js

added:
- mobile api
- mobile api with cookie
- web app graphql api with cookie
...for total of fucking SIX???

instagram: add three more ways to get post info

---

src/cobalt.js
src/core/api.js
src/core/web.js
src/modules/config.js
src/modules/pageRender/elements.js
src/modules/pageRender/page.js
src/modules/processing/cookie/manager.js
src/modules/processing/services/tiktok.js
src/modules/stream/manage.js
src/modules/stream/types.js

centralized environment variables in `modules/config` as discussed with @dumbmoron in #463 pull request

Centralized environment variables and their default values in `modules/config`

---

src/modules/processing/matchActionDecider.js
src/modules/processing/services/soundcloud.js
src/modules/processing/services/tiktok.js
src/modules/processing/services/youtube.js
src/modules/processing/servicesConfig.json

- youtube: fall back to m4a if opus isn't available
- tiktok & soundcloud: proper best audio picking
- tiktok: improved audio file naming scheme

best audio picking improvements for youtube, tiktok, and soundcloud

---

src/modules/processing/match.js
src/modules/processing/services/reddit.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js

reddit: add support for user post links & clean up

---

src/modules/config.js
src/modules/processing/servicesConfig.json
src/modules/stream/manage.js
src/modules/stream/types.js

added reddit to hls exceptions to disable istream for it, as it breaks live rendering
closes #526

stream: move hls exceptions to servicesConfig

---

README.md
src/modules/processing/match.js
src/modules/processing/matchActionDecider.js
src/modules/processing/services/loom.js
src/modules/processing/servicesConfig.json
src/modules/processing/servicesPatternTesters.js
src/test/tests.json

add loom support

---

package-lock.json
src/modules/stream/internal-hls.js
src/modules/stream/internal.js
src/modules/stream/manage.js

related to #510
this pr adds conversion of chunk links within HLS playlists into istreams

stream: add hls support for internal streams

---

src/modules/stream/internal-hls.js

internal-hls: correctly handle URL concatenation of all types

---

src/modules/stream/manage.js

fixes controller handling for istream HLS playlists

stream/manage: inherit controller from parent istream if it exists

---

src/modules/processing/services/youtube.js

youtube: fix audio track selection for dubbed videos & clean up

---

api/src/processing/services/youtube.js
web/i18n/en/settings.json

api/youtube: use opus audio & webm container for av1

---

api/src/util/setup.js

[dd831e1](https://github.com/imputnet/cobalt/commit/dd831e13e89bfc5a37246280e41468a3d1d8c4bd#diff-91ed721a91c458c8adbcbea7483425afe4b432a53782fdd5e42c50f3fc51da18)

api/setup: fix wrong misc path

---

api/src/processing/service-config.js
api/src/processing/url.js
api/src/util/tests.json

feat/api: add support for twitter bookmark links

---

api/src/processing/match-action.js
api/src/processing/match.js
api/src/processing/request.js
api/src/processing/schema.js
api/src/processing/service-config.js
api/src/processing/services/bluesky.js
api/src/processing/services/dailymotion.js
api/src/processing/services/rutube.js
api/src/processing/services/vimeo.js
api/src/processing/services/youtube.js
api/src/stream/internal.js
api/src/stream/manage.js
api/src/stream/types.js
api/src/util/tests.json
web/i18n/en/error.json
web/i18n/en/settings.json
web/src/lib/api/api.ts
web/src/lib/settings/defaults.ts
web/src/lib/types/settings.ts
web/src/routes/settings/video/+page.svelte

HLS streams don't get cut off (at this time), so this is a partial fix for #647

api/youtube: add an option to use HLS streams

---

api/src/processing/services/bluesky.js
api/src/stream/internal-hls.js
api/src/stream/internal.js

api/bluesky: go around rate limiting by using the video cdn directly

---

web/i18n/en/error.json

i didn't expect to rewrite this much ngl

web/i18n/error: rephrase a bunch of strings for more clarity and context

---

api/src/core/api.js
api/src/core/itunnel.js
api/src/processing/services/bilibili.js
api/src/stream/internal-hls.js
api/src/stream/internal.js
api/src/stream/manage.js
api/src/stream/shared.js
api/src/stream/stream.js
api/src/stream/types.js

api/stream: add `Estimated-Content-Length` header to tunnels

---

api/src/processing/services/tiktok.js

api/tiktok: update domain because dns records for main one are gone

---

api/src/misc/run-test.js
api/src/misc/utils.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/bilibili.js
api/src/processing/services/instagram.js
api/src/processing/services/pinterest.js
api/src/processing/services/snapchat.js
api/src/processing/services/xiaohongshu.js
api/src/processing/services/youtube.js
api/src/processing/url.js
api/src/util/test.js
api/src/util/tests/bilibili.json
api/src/util/tests/instagram.json
api/src/util/tests/snapchat.json

this should hopefully fix downloading all viewable posts once again
closes #222
closes #539
closes #646
closes #998
closes #1046
closes #1072
closes #1083
closed duplicate issues:
closes #1093
closes #1080
closes #1019
closes #949
closes #825
closes #809
closes #800
closes #710
closes #609
closes #580
closes #572

api/instagram: yet another attempt at resurrection

---

api/src/processing/match.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/reddit.js

api/reddit: add support for mobile links & a bunch of other links

---

api/src/processing/services/snapchat.js
api/src/util/tests/snapchat.json

api/snapchat: allow profile params to be missing

---

api/src/processing/services/ok.js

closes #866
https://github.com/imputnet/cobalt/blob/main/api/src/processing/services/ok.js#L47
`author` may be undefined
videoData: 
```
{
"provider": "UPLOADED_ODKL",
"service": "ok",
"owner": false,
"voted": false,
"likeCount": 0,
"subscribed": false,
"isWatchLater": false,
"slot": 690,
"siteZone": -1,
"showAd": true,
"fromTime": 0,
"author": {},
"movie": {
"id": "376357718731",
"movieId": "376357718731",
"likeId": "376357718731",
"contentId": "340295027403",
"poster": "https://i.okcdn.ru/videoPreview?id=340295027403&type=32&idx=13&tkn=T6Z6ADXIQZOdmr9owIB_hbz0dVk&fn=external_8",
"duration": "4201",
"title": "Peppa.Pig.My.First.Cinema.Experience.2017.HDRip.ShahidFirst.TV",
"url": "https://ok.ru/video/376357718731",
"link": "/video/376357718731",
"collageInfo": {
"imageType": "COLLAGE", …
```

api/ok: fix author not being handled properly

---

api/src/core/api.js

api/core: return 429 http status for rate-limit

---

api/src/processing/services/twitter.js
api/src/util/tests/twitter.json

twitter: add fallback to syndication api, fix some edge cases, and add a gif test

---

api/src/processing/match.js
api/src/processing/services/youtube.js
api/src/util/tests/xiaohongshu.json

should reduce `WEB_EMBEDDED` rate limit errors by a lot

api/youtube: use the iOS client in more cases

---

api/src/misc/utils.js
api/src/processing/service-config.js
api/src/processing/service-patterns.js
api/src/processing/services/instagram.js
api/src/processing/services/reddit.js
api/src/processing/url.js
api/src/util/tests/reddit.json

fixes #910.
* [`api/src/processing/service-config.js`](diffhunk://#diff-e46dbb2452195cabae3b56ac712455a8c21a68c6e4f44f8c099490922eeb69a3L93-R95): added a new pattern (`video/:shortId`).
* [`api/src/processing/service-patterns.js`](diffhunk://#diff-e05a6ed3d1467276680efa54cd175906836db6081d431d1ed200fdf2f5a05841L26-R27):  include a condition for `shortId`.
* [`api/src/processing/services/reddit.js`](diffhunk://#diff-9d3ca2025c5ab39b8e96df420e3b9ed3ab318b0cc93e95b632f959b46ac67a3aR53-R70): modified the main function to fetch short links. 
* [`api/src/processing/url.js`](diffhunk://#diff-9ac8d3080f8db4582fa8456673575716b3acce861b8ffe260eb6db1b7945e1daR109-R116): added a case to handle the aliasing of short links (by converting `v.redd.it/<id>` to `reddit.com/video/<id>`).

api/reddit: add support for short links

---

api/package.json
api/src/processing/services/youtube.js
pnpm-lock.yaml

package: update youtubei.js to 13.4.0

---

api/src/processing/service-config.js
api/src/processing/services/snapchat.js

api: fix snapchat short link parsing

---

pnpm-lock.yaml
web/package.json
web/src/components/dialog/NoScriptDialog.svelte
web/src/lib/types/changelogs.ts

just updating the dependencies for now, will migrate components gradually over time

web: initial svelte 5 update

---

api/src/processing/services/twitter.js

api/twitter: use newer graphql endpoint, refactor
